### ISSUE TITLE
Failed insert at sync

### ISSUE THREAD

**Issue by abernatskiy** [subsquid/uniswap-squid#1]
**Symptoms:** syncing fails with at block 15861869 with the following error message:
```
01:34:16 FATAL sqd:processor QueryFailedError: insert or update on table "position" violates foreign key constraint "FK_128820371117dcf3915dc01ad30"
                                 at PostgresQueryRunner.query (/laptopstorage/uniswap-squid/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
                                 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                                 at async InsertQueryBuilder.execute (/laptopstorage/uniswap-squid/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
                                 at async Store.upsertMany (/laptopstorage/uniswap-squid/node_modules/@subsquid/typeorm-store/lib/store.js:62:13)
                                 at async Store.saveMany (/laptopstorage/uniswap-squid/node_modules/@subsquid/typeorm-store/lib/store.js:49:13)
                                 at async Store.save (/laptopstorage/uniswap-squid/node_modules/@subsquid/typeorm-store/lib/store.js:23:13)
                                 at async PositionProcessor.run (/laptopstorage/uniswap-squid/lib/mappings/positionManager.js:64:9)
                                 at async /laptopstorage/uniswap-squid/lib/processor.js:96:5
                                 at async TypeormDatabase.runTransaction (/laptopstorage/uniswap-squid/node_modules/@subsquid/typeorm-store/lib/database.js:110:13)
                                 at async TypeormDatabase.transact (/laptopstorage/uniswap-squid/node_modules/@subsquid/typeorm-store/lib/database.js:64:24)
```
Restarting the squid causes the same error. Full log of one of the restarts: [log](https://pastebin.com/raw/Lwx7vNN0). `.env` file contents:
```
DB_PORT=23231
GQL_PORT=4875
CHAIN_NODE=wss://eth-mainnet.nodereal.io/ws/v1/<token>
```
Reproducing takes about a day on Nodereal, currently attempting it.

**Comment by abernatskiy** [comment]
Just finished reproducing the issue, full error message is [on pastebin](https://pastebin.com/raw/d6VQ1Nng).
